project_id = "rainzsxcqrfrvihmvhee"

[functions.login-by-nick]
verify_jwt = false

[functions.register-member]
verify_jwt = false

[functions.manage-member-applications]
verify_jwt = false

[functions.app-api]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false
