(function(){"use strict";
const cfg=window.RAINDOGS_SUPABASE;if(!cfg)return;
function stored(){try{return JSON.parse(localStorage.getItem("rdSupabaseSession")||sessionStorage.getItem("rdSupabaseSession")||"null")}catch{return null}}
async function call(action,body){const s=stored();if(!s?.access_token)throw new Error("Oturum gerekli.");const r=await fetch(`${cfg.url}/functions/v1/app-api?action=${encodeURIComponent(action)}`,{method:body?"POST":"GET",headers:{"Content-Type":"application/json",apikey:cfg.publishableKey,Authorization:`Bearer ${s.access_token}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"İşlem tamamlanamadı.");return d}
const scopeName=x=>x?.charters?.name||"";
function eventRow(x){const d=new Date(x.starts_at);return {id:x.id,title:x.title,body:x.description||"",description:x.description||"",date:d.toLocaleDateString("tr-TR"),iso:x.starts_at?.slice(0,10),time:d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"}),location:x.location||"",route:x.route_text||"",distance:x.distance_km||0,importance:x.importance,participationStatus:x.participation_status,status:x.status,ownerCharter:scopeName(x),kind:x.scope,backend:true}}
function newsRow(x){return {id:x.id,title:x.title,body:x.body,date:new Date(x.created_at).toLocaleDateString("tr-TR"),importance:x.importance,required:x.required_read,status:x.status,charter:scopeName(x),publishScope:x.scope,backend:true}}
function routeRow(x){return {id:x.id,name:x.name,km:x.distance_km,distance:x.distance_km,difficulty:x.difficulty,duration:x.duration||"",surface:x.surface||"",character:x.character||"",notes:x.notes||"",status:x.status,charter:scopeName(x),scope:x.scope,backend:true}}
async function hydrate(){if(!currentUser?.backend)return;try{const d=await call("bootstrap");const ee=(d.events||[]).map(eventRow),nn=(d.announcements||[]).map(newsRow),rr=(d.routes||[]).map(routeRow);customEvents=ee.filter(x=>x.kind!=="charter");charterEvents=ee.filter(x=>x.kind==="charter");events=[...events.filter(x=>!x.backend&&!String(x.id||"").includes("custom_")),...customEvents];customNews=nn.filter(x=>x.publishScope!=="charter");charterNews=nn.filter(x=>x.publishScope==="charter");charterRoutes=rr.filter(x=>x.scope==="charter");kmEntries=(d.kmEntries||[]).map(x=>({id:x.id,route:x.route_name,km:x.km,status:x.status==="active"?"Onaylandı":"Onay Bekliyor",date:new Date(x.created_at).toLocaleDateString("tr-TR"),memberNick:currentUser.nick,backend:true}));clubhouseVisits=(d.clubhouseVisits||[]).map(x=>({id:x.id,chapter:scopeName(x),nick:x.profiles?.nick||"",guests:x.guest_count,entryAt:x.entered_at,exitAt:x.exited_at,backend:true}));notifications=(d.notifications||[]).map(x=>({id:x.id,type:x.type,title:x.title,body:x.body,read:!!x.read_at,date:new Date(x.created_at).toLocaleDateString("tr-TR"),action:x.action_path,backend:true}));memberNotes=d.memberNotes||[];helpTickets=d.helpTickets||[];render("home");safeToast("Merkezi veriler güncellendi.")}catch(e){safeToast(e.message)}}
window.rdBackend={call,hydrate};window.addEventListener("raindogs:authenticated",hydrate);
const localKm=window.addKm;window.addKm=async function(){if(!currentUser?.backend)return localKm();const route=document.getElementById("routeInput")?.value.trim(),km=Number(document.getElementById("kmInput")?.value);if(!route||!km)return safeToast("Rota ve kilometre gir.");try{await call("km.submit",{routeName:route,km});await hydrate();render("km");safeToast("Kilometre kaydı onaya gönderildi.")}catch(e){safeToast(e.message)}};
const localEnter=window.enterClubhouse;window.enterClubhouse=async function(){if(!currentUser?.backend)return localEnter();try{await call("clubhouse.enter",{guestCount:Number(document.getElementById("clubhouseGuestCount")?.value||0)});await hydrate();render("charterHub");safeToast("Giriş kaydedildi.")}catch(e){safeToast(e.message)}};
const localLeave=window.leaveClubhouse;window.leaveClubhouse=async function(){if(!currentUser?.backend)return localLeave();try{await call("clubhouse.leave",{});await hydrate();render("charterHub");safeToast("Çıkış kaydedildi.")}catch(e){safeToast(e.message)}};
})();
