(function(){"use strict";
const cfg=window.RAINDOGS_SUPABASE;if(!cfg)return;
function stored(){try{return JSON.parse(localStorage.getItem("rdSupabaseSession")||sessionStorage.getItem("rdSupabaseSession")||"null")}catch{return null}}
async function call(action,body){const s=stored();if(!s?.access_token)throw new Error("Oturum gerekli.");const r=await fetch(`${cfg.url}/functions/v1/app-api?action=${encodeURIComponent(action)}`,{method:body?"POST":"GET",headers:{"Content-Type":"application/json",apikey:cfg.publishableKey,Authorization:`Bearer ${s.access_token}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"İşlem tamamlanamadı.");return d}
const scopeName=x=>x?.charters?.name||"";
function eventRow(x){const d=new Date(x.starts_at);return {id:x.id,title:x.title,body:x.description||"",description:x.description||"",date:d.toLocaleDateString("tr-TR"),iso:x.starts_at?.slice(0,10),time:d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"}),location:x.location||"",route:x.route_text||"",distance:x.distance_km||0,importance:x.importance,participationStatus:x.participation_status,status:x.status,ownerCharter:scopeName(x),kind:x.scope,backend:true}}
function newsRow(x){return {id:x.id,title:x.title,body:x.body,date:new Date(x.created_at).toLocaleDateString("tr-TR"),importance:x.importance,required:x.required_read,status:x.status,charter:scopeName(x),publishScope:x.scope,backend:true}}
function routeRow(x){return {id:x.id,name:x.name,km:x.distance_km,distance:x.distance_km,difficulty:x.difficulty,duration:x.duration||"",surface:x.surface||"",character:x.character||"",notes:x.notes||"",status:x.status,charter:scopeName(x),scope:x.scope,backend:true}}
const levelTr=x=>x==="member"?"Member":x==="prospect"?"Prospect":"Hangaround";
const levelDb=x=>String(x||"").toLowerCase()==="member"?"member":String(x||"").toLowerCase()==="prospect"?"prospect":"hangaround";
function profileRow(x){return {id:x.id,backendId:x.id,nick:x.nick,name:x.full_name,phone:x.phone||"",motorcycle:x.motorcycle||"",role:x.charter_role||levelTr(x.member_level),memberLevel:levelTr(x.member_level),status:x.account_status==="active"?"Aktif":x.account_status==="frozen"?"Askıda":x.account_status==="left"?"Ayrıldı":x.account_status==="rejected"?"Reddedildi":"Onay Bekliyor",chapter:scopeName(x),nationalRole:x.national_role||"",appAdmin:!!x.is_app_admin,isAdmin:!!x.is_app_admin||!!x.national_role||!!x.charter_role,backend:true}}
async function hydrate(){if(!currentUser?.backend)return;try{const d=await call("bootstrap");const ee=(d.events||[]).map(eventRow),nn=(d.announcements||[]).map(newsRow),rr=(d.routes||[]).map(routeRow);customEvents=ee.filter(x=>x.kind!=="charter");charterEvents=ee.filter(x=>x.kind==="charter");events=[...events.filter(x=>!x.backend&&!String(x.id||"").includes("custom_")),...customEvents];customNews=nn.filter(x=>x.publishScope!=="charter");charterNews=nn.filter(x=>x.publishScope==="charter");charterRoutes=rr.filter(x=>x.scope==="charter");kmEntries=(d.kmEntries||[]).map(x=>({id:x.id,route:x.route_name,km:x.km,status:x.status==="active"?"Onaylandı":x.status==="rejected"?"Reddedildi":"Onay Bekliyor",date:new Date(x.created_at).toLocaleDateString("tr-TR"),memberNick:currentUser.nick,backend:true}));clubhouseVisits=(d.clubhouseVisits||[]).map(x=>({id:x.id,chapter:scopeName(x),nick:x.profiles?.nick||"",guests:x.guest_count,entryAt:x.entered_at,exitAt:x.exited_at,backend:true}));notifications=(d.notifications||[]).map(x=>({id:x.id,type:x.type,title:x.title,body:x.body,read:!!x.read_at,date:new Date(x.created_at).toLocaleDateString("tr-TR"),action:x.action_path,backend:true}));memberNotes=d.memberNotes||[];helpTickets=(d.helpTickets||[]).map(x=>({...x,nick:x.reporter_id===d.actor?.id?currentUser.nick:x.reporter_id,createdAt:new Date(x.created_at).toLocaleString("tr-TR"),updatedAt:new Date(x.updated_at).toLocaleString("tr-TR")}));window.rdBackendProfiles=(d.profiles||[]).map(profileRow);applications=(d.applications||[]).map(x=>({...profileRow(x),backendId:x.id,joined:new Date(x.created_at).toLocaleDateString("tr-TR"),status:"Onay Bekliyor"}));if(window.rdBackendProfiles.length){const localIds=new Set(window.rdBackendProfiles.map(x=>x.nick));accounts=[...accounts.filter(x=>!x.backend&&!localIds.has(x.nick)),...window.rdBackendProfiles]}window.rdClubhouseStates=d.clubhouseStates||[];if(Array.isArray(d.adminLogs)&&d.adminLogs.length)adminLogs=d.adminLogs.map(x=>({action:x.action,target:x.detail?.title||x.target_id||"",admin:x.profiles?.nick||"Sistem",date:new Date(x.created_at).toLocaleString("tr-TR")}));render("home");safeToast("Merkezi veriler güncellendi.")}catch(e){safeToast(e.message)}}
window.rdBackend={call,hydrate};window.addEventListener("raindogs:authenticated",hydrate);
const localKm=window.addKm;window.addKm=async function(){if(!currentUser?.backend)return localKm();const route=document.getElementById("routeInput")?.value.trim(),km=Number(document.getElementById("kmInput")?.value);if(!route||!km)return safeToast("Rota ve kilometre gir.");try{await call("km.submit",{routeName:route,km});await hydrate();render("km");safeToast("Kilometre kaydı onaya gönderildi.")}catch(e){safeToast(e.message)}};
const localEnter=window.enterClubhouse;window.enterClubhouse=async function(){if(!currentUser?.backend)return localEnter();try{await call("clubhouse.enter",{guestCount:Number(document.getElementById("clubhouseGuestCount")?.value||0)});await hydrate();render("charterHub");safeToast("Giriş kaydedildi.")}catch(e){safeToast(e.message)}};
const localLeave=window.leaveClubhouse;window.leaveClubhouse=async function(){if(!currentUser?.backend)return localLeave();try{await call("clubhouse.leave",{});await hydrate();render("charterHub");safeToast("Çıkış kaydedildi.")}catch(e){safeToast(e.message)}};

const isoDate=(date,time="09:00")=>{if(/^\d{4}-\d{2}-\d{2}$/.test(date||""))return new Date(`${date}T${time||"09:00"}:00`).toISOString();const d=new Date(date);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()};
function eventData(x){return {title:x.title,description:x.description||x.body||"",scope:x.kind||x.scope||"national",owner_charter_id:x.ownerCharterId||null,starts_at:isoDate(x.iso||x.date,x.time),ends_at:x.endsAt||null,location:x.location||"",route_text:x.route||"",distance_km:Number(String(x.distance||x.km||0).replace(/\D/g,""))||0,importance:x.importance||"Normal",participation_status:x.participationStatus||"Açık",status:x.status==="Arşivlendi"?"archived":"active",poster_path:x.poster||null}}
function newsData(x){return {title:x.title,body:x.body||"",scope:x.publishScope||x.scope||"national",charter_id:x.charterId||null,importance:x.importance||x.tag||"Normal",required_read:!!x.required,status:x.status==="Arşivlendi"?"archived":"active",photo_path:x.photo||null,expires_at:x.expiresAt||null}}
function routeData(x){return {name:x.name,scope:x.scope||"charter",charter_id:x.charterId||null,distance_km:Number(x.distance||x.km||0),difficulty:x.difficulty||"Orta",duration:x.duration||"",surface:x.surface||"",character:x.character||"",notes:x.notes||"",photo_path:x.photo||null,status:x.status==="Arşivlendi"?"archived":"active"}}
async function persist(kind,item){if(!currentUser?.backend||!item)return;const data=kind==="event"?eventData(item):kind==="announcement"?newsData(item):routeData(item);const id=item.backend?item.id:undefined;await call("content.save",{kind,id,data});await hydrate()}
function wrapCreate(name,kind,getRows){const original=window[name];if(typeof original!=="function")return;window[name]=async function(...args){if(!currentUser?.backend)return original.apply(this,args);const before=new Set(getRows().map(x=>String(x.id)));original.apply(this,args);const item=getRows().find(x=>!before.has(String(x.id)));if(!item)return;try{await persist(kind,item);safeToast("İçerik merkezi olarak kaydedildi.")}catch(e){safeToast(e.message)}}}
wrapCreate("createNews","announcement",()=>customNews);wrapCreate("createEvent","event",()=>customEvents);wrapCreate("createCharterNews","announcement",()=>charterNews);wrapCreate("createCharterEvent","event",()=>charterEvents);wrapCreate("createCharterRoute","route",()=>charterRoutes);
function wrapEdit(name,kind,getItem){const original=window[name];if(typeof original!=="function")return;window[name]=async function(id,...args){if(!currentUser?.backend)return original.call(this,id,...args);original.call(this,id,...args);const item=getItem(id);if(!item)return;try{await persist(kind,item);safeToast("Değişiklik merkezi olarak kaydedildi.")}catch(e){safeToast(e.message)}}}
wrapEdit("editLocalEvent","event",id=>charterEvents.find(x=>String(x.id)===String(id)));wrapEdit("editCharterNews","announcement",id=>charterNews.find(x=>String(x.id)===String(id)));wrapEdit("editCharterRoute","route",id=>charterRoutes.find(x=>String(x.id)===String(id)));
const localApproveKm=window.approveKm;window.approveKm=async function(id){if(!currentUser?.backend)return localApproveKm(id);try{await call("km.approve",{id,approve:true});await hydrate();render("adminKm");safeToast("Kilometre onaylandı.")}catch(e){safeToast(e.message)}};
const localMarkRead=window.markNotificationRead;window.markNotificationRead=async function(id){const n=notifications.find(x=>String(x.id)===String(id));if(!currentUser?.backend||!n?.backend)return localMarkRead(id);try{await call("notification.read",{id});await hydrate();render("notifications")}catch(e){safeToast(e.message)}};
const localAllRead=window.markAllNotificationsRead;window.markAllNotificationsRead=async function(){if(!currentUser?.backend)return localAllRead();try{for(const n of notifications.filter(x=>x.backend&&!x.read))await call("notification.read",{id:n.id});await hydrate();openNotificationsSheet()}catch(e){safeToast(e.message)}};
const localTicket=window.submitHelpTicket;window.submitHelpTicket=async function(){if(!currentUser?.backend)return localTicket();const subject=document.getElementById("helpTitle")?.value.trim(),body=document.getElementById("helpBody")?.value.trim();if(!subject||!body)return safeToast("Başlık ve açıklama zorunlu.");try{await call("ticket.create",{subject,body});await hydrate();openHelpCenter();safeToast("Bildirimin admine iletildi.")}catch(e){safeToast(e.message)}};
const localNote=window.addMemberNote;window.addMemberNote=async function(){if(!currentUser?.backend)return localNote();const nick=document.getElementById("noteMember")?.value,member=window.rdBackendProfiles?.find(x=>x.nick===nick),body=document.getElementById("noteBody")?.value.trim();if(!member||!body)return safeToast("Üye ve not zorunlu.");try{await call("note.create",{memberId:member.id,noteType:document.getElementById("noteType")?.value||"Genel",body});await hydrate();render("memberNotes");safeToast("Üye notu kaydedildi.")}catch(e){safeToast(e.message)}};
window.rdBackendUpdateMember=async function(nick,patch){const member=window.rdBackendProfiles?.find(x=>x.nick===nick);if(!member)throw new Error("Merkezi üye bulunamadı.");return call("member.update",{memberId:member.id,...patch})};
const localStatus=window.setMemberAccountStatus;window.setMemberAccountStatus=async function(nick,status){if(!currentUser?.backend)return localStatus(nick,status);const map={"Aktif":"active","Askıda":"frozen","Ayrıldı":"left","Reddedildi":"rejected"};try{await window.rdBackendUpdateMember(nick,{accountStatus:map[status]||status});await hydrate();render("members");safeToast("Üyelik durumu güncellendi.")}catch(e){safeToast(e.message)}};
const localRoles=window.saveSelectedRolesV70;window.saveSelectedRolesV70=async function(nick){if(!currentUser?.backend)return localRoles(nick);const role=document.getElementById(`roleSelectV70_${nick}`)?.value||"Member",nationalRole=document.getElementById(`nationalSelectV70_${nick}`)?.value||"";try{await window.rdBackendUpdateMember(nick,{memberLevel:levelDb(role),charterRole:["Member","Prospect","Hangaround"].includes(role)?null:role,nationalRole});await hydrate();render("members");safeToast("Görevler merkezi olarak güncellendi.")}catch(e){safeToast(e.message)}};
const localApproveApp=window.approveApplication;window.approveApplication=async function(i){const app=applications[i];if(!currentUser?.backend||!app?.backendId)return localApproveApp(i);try{await call("application.decide",{memberId:app.backendId,approve:true});await hydrate();render("adminApplications");safeToast("Üyelik onaylandı.")}catch(e){safeToast(e.message)}};
const localRejectApp=window.rejectApplication;window.rejectApplication=async function(i){const app=applications[i];if(!currentUser?.backend||!app?.backendId)return localRejectApp(i);try{await call("application.decide",{memberId:app.backendId,approve:false});await hydrate();render("adminApplications");safeToast("Başvuru reddedildi.")}catch(e){safeToast(e.message)}};
const localAddChapter=window.addChapterFromPanel;window.addChapterFromPanel=async function(){if(!currentUser?.backend)return localAddChapter();const name=document.getElementById("newChapterName")?.value?.trim()||document.getElementById("chapterName")?.value?.trim();if(!name)return safeToast("Charter adı zorunlu.");try{await call("charter.create",{name});await hydrate();safeToast("Charter oluşturuldu.")}catch(e){safeToast(e.message)}};
})();
